# Generated by Django 2.2.16 on 2022-08-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220823_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_text_author',
        ),
    ]
